### PR TITLE
Updated sharing events to fire.

### PR DESCRIPTION
**Pull request by E-B-Smith**

### CODE REVIEW

**Comment by BranchMacMini** [comment]
Result of [Integration 1](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/1b77343b32a1796bc2c189cc4bd2af28/1b77343b32a1796bc2c189cc4bd2b672)
---
*Duration*: 35 minutes and 51 seconds
*Result*: **2 errors, failing state: build-errors**

**Comment by BranchMacMini** [comment]
Result of [Integration 2](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/1b77343b32a1796bc2c189cc4bd2af28/1b77343b32a1796bc2c189cc4be8117f)
---
*Duration*: 14 minutes and 45 seconds
*Result*: All 227 tests passed, but please **fix 2 warnings**.
*Test Coverage*: 63%

**Comment by sojanpr** [comment]
Look like this will fix issue. Can we check any other event missing `logEvent`

**Comment by E-B-Smith** [comment]
I've already checked!

**Pull request merged**
