### PR TITLE
Send user agent

### PR DESCRIPTION
**Pull request by aaustin**
@derrickstaten as discussed

### CODE REVIEW

**Comment by ahmednawar** [comment]
@aaustin was this branched from staging or master?

**Comment by derrickstaten** [comment]
Before we send this on every request, can we time how much it slows down requests? If it adds < 10ms, I'm okay with it. If it adds 200ms, then we have to reconsider.

**Comment by ahmednawar** [comment]
Can we cache it on `PreferenceHelper`?

**Comment by aaustin** [comment]
good point - let me find a better way.

**Comment by aaustin** [comment]
this was off of master @ahmednawar

**Comment by ahmednawar** [comment]
Ok, I should merge `master` into `staging` after every release then push to Github. The release script updates `master` and pushes to Github directly. The 2 branches will out of sync for files like `BNCConfig` and `ChangeLog`

**Pull request closed without merging**
