### PR TITLE
Fixed `getUpdateState` so it works on Enterprise apps too.

### PR DESCRIPTION
**Pull request by E-B-Smith**
* enterprise-update-INTENG-3189

### CODE REVIEW

**Comment by E-B-Smith** [comment]
Tested with Enterprise builds:
```
 Enterprise        install   open
    10.3 beta 7         x       x
    10.2.1              x       x
    10.1                x       x
    9.1                 x       x
    8.1                 x       x
    7.1                 x       x
```

**Comment by BranchMacMini** [comment]
Result of [Integration 1](https://stlt.herokuapp.com/v1/xcs_deeplink/BranchMacMini.local/8584c1925d0f30c3bae2e4b6ba24c1e1/8584c1925d0f30c3bae2e4b6ba24ccef)
---
*Duration*: 3 minutes and 32 seconds
*Result*: **Build failed 5 tests** out of 143

**Comment by BranchMacMini** [comment]
Result of [Integration 2](https://stlt.herokuapp.com/v1/xcs_deeplink/BranchMacMini.local/8584c1925d0f30c3bae2e4b6ba24c1e1/8584c1925d0f30c3bae2e4b6ba403620)
---
*Duration*: 44 seconds
*Result*: **3 errors, failing state: build-errors**

**Comment by BranchMacMini** [comment]
Result of [Integration 4](https://stlt.herokuapp.com/v1/xcs_deeplink/BranchMacMini.local/8584c1925d0f30c3bae2e4b6ba24c1e1/8584c1925d0f30c3bae2e4b6ba7a85b9)
---
*Duration*: 3 minutes and 17 seconds
*Result*: **Build failed 2 tests** out of 147

**Comment by BranchMacMini** [comment]
Result of [Integration 5](https://stlt.herokuapp.com/v1/xcs_deeplink/BranchMacMini.local/8584c1925d0f30c3bae2e4b6ba24c1e1/8584c1925d0f30c3bae2e4b6ba8c7e24)
---
*Duration*: 2 minutes and 40 seconds
*Result*: **Build failed 1 test** out of 147

**Comment by BranchMacMini** [comment]
Result of [Integration 6](https://stlt.herokuapp.com/v1/xcs_deeplink/BranchMacMini.local/8584c1925d0f30c3bae2e4b6ba24c1e1/8584c1925d0f30c3bae2e4b6ba9dc417)
---
*Duration*: 1 minute and 57 seconds
*Result*: **Perfect build!** All 147 tests passed. :+1:
*Test Coverage*: 60%

**Comment by aaustin** [comment]
@jdee Can you review?

**Comment by BranchMacMini** [comment]
Result of [Integration 7](https://stlt.herokuapp.com/v1/xcs_deeplink/BranchMacMini.local/8584c1925d0f30c3bae2e4b6ba24c1e1/8584c1925d0f30c3bae2e4b6bab030e8)
---
*Duration*: 2 minutes and 32 seconds
*Result*: **Build failed 2 tests** out of 147

**Comment by E-B-Smith** [comment]
Tested with app store style builds for versions:

```
iOS Version        install   open
    10.3 beta 7         x       x
    10.2.1              x       x
    10.1                x       x
    9.1                 x       x
    8.1                 x       x
    7.1                 x       x
```

**Comment by BranchMacMini** [comment]
Result of [Integration 8](https://stlt.herokuapp.com/v1/xcs_deeplink/BranchMacMini.local/8584c1925d0f30c3bae2e4b6ba24c1e1/8584c1925d0f30c3bae2e4b6bac29a4e)
---
*Duration*: 2 minutes and 34 seconds
*Result*: **Perfect build!** All 147 tests passed. :+1:
*Test Coverage*: 60%

**Pull request merged**
