### PR TITLE
Updated nullability for Swift.

### PR DESCRIPTION
**Pull request by E-B-Smith**
I made the callback params nullable for Swift compatibility.

### CODE REVIEW

**Comment by aaustin** [comment]
Hmm - I don't think params can ever be null though, which is why I set them to `_Nonnull`. Can you share the line where they return null values?

**Comment by aaustin** [comment]
Also, you need to tag someone if you want this reviewed. Maybe you didn't?

**Comment by E-B-Smith** [comment]
Accidental nil values being passed to a call back can be tricky to detect, and are a certain crash on the Swift side, so I made the parameters nullable for the time being to prevent crashes.

**Comment by ahmednawar** [comment]
IIUC, all server responses should hit this method https://github.com/BranchMetrics/ios-branch-deep-linking/blob/master/Branch-SDK/Branch-SDK/BNCEncodingUtils.m#L389-L415 which would return `{}` in case of `nil` or bad data

**Comment by E-B-Smith** [comment]
I'm thinking of this, instance:

https://github.com/BranchMetrics/ios-branch-deep-linking/blob/master/Branch-SDK/Branch-SDK/Branch.m#L1302-L1304
```
        if (self.sessionInitWithParamsCallback) {
            self.sessionInitWithParamsCallback([self getLatestReferringParams], nil);
        }
```

If `[self getLatestReferringParams]` return nil for some reason, it's a crash in Swift.

**Comment by aaustin** [comment]
I think it's impossible for that to happen? https://github.com/BranchMetrics/ios-branch-deep-linking/blob/master/Branch-SDK/Branch-SDK/Branch.m#L775 and https://github.com/BranchMetrics/ios-branch-deep-linking/blob/master/Branch-SDK/Branch-SDK/BNCEncodingUtils.m#L389. Since we already have those flags and the parter wrote in saying we don't, I think there's a different root cause at play here. Let's wait for him to reply to us.

**Comment by E-B-Smith** [comment]
The best solution is to add strict nullability checking throughout the SDK which will allow the static analyzer to catch these cases for us.  Checking all the edge cases can be pretty time consuming for us humans but is easy for the analyzer.

Until then, I think we should change the 'nullable' flag here to prevent accidental partner crashes.  It's the fastest fix and prevents some pretty awful partner crashes.

**Pull request merged**
