### PR TITLE
Fix blacklist open with URI scheme DEVEX-341

### PR DESCRIPTION
**Pull request by E-B-Smith**
* Added code that clears the blacklisted URL after sending the regex pattern to the server.
* Removed an old NSLog from debugging.

### CODE REVIEW

**Comment by BranchMacMini** [comment]
Result of [Integration 1](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/e717707c6307590c56cff9199a01c27b/e717707c6307590c56cff9199a01ca03)
---
*Duration*: 26 minutes and 40 seconds
*Result*: **-1 error, failing state: internal-build-error**

**Comment by BranchMacMini** [comment]
Result of [Integration 2](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/e717707c6307590c56cff9199a01c27b/e717707c6307590c56cff9199a029064)
---
*Duration*: 14 minutes and 49 seconds
*Result*: All 227 tests passed, but please **fix 3 warnings**.
*Test Coverage*: 62%

**Comment by philipengberg** [comment]
May I ask what this "blacklisted URL" is, means, or does? 🙂

**Comment by sojanpr** [comment]
Can we set only `external_intent_uri` in case the URL matches black list as we  do it in Andorid. That way we can avoid getting status 400 on v1/open calls

**Comment by BranchMacMini** [comment]
Result of [Integration 3](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/e717707c6307590c56cff9199a01c27b/e717707c6307590c56cff9199a710ec0)
---
*Duration*: 15 minutes and 24 seconds
*Result*: **Build failed 2 tests** out of 227

**Comment by E-B-Smith** [comment]
Moved the matching regex to `external_intent_uri`.

**Comment by sojanpr** [comment]
LGTM 👍

**Comment by E-B-Smith** [comment]
Awesome!

**Pull request merged**
