### PR TITLE
Add light weight logging - AIS 193

### PR DESCRIPTION
**Pull request by E-B-Smith**
cc: @ahmednawar @aaustin

### CODE REVIEW

**Comment by BranchMacMini** [comment]
Result of [Integration 1](https://stlt.herokuapp.com/v1/xcs_deeplink/BranchMacMini.local/ea5ae53b09b7154843780a0f5b043891/ea5ae53b09b7154843780a0f5b0483ea)
---
*Duration*: 27 minutes and 8 seconds
*Result*: **-1 error, failing state: internal-build-error**

**Comment by BranchMacMini** [comment]
Result of [Integration 1](https://stlt.herokuapp.com/v1/xcs_deeplink/BranchMacMini.local/1d6f071064e67f7d4dee3ef2e1546cbd/1d6f071064e67f7d4dee3ef2e1547a02)
---
*Duration*: 5 minutes and 18 seconds
*Result*: All 165 tests passed, but please **fix 1 analyzer warning**.
*Test Coverage*: 65%

**Comment by BranchMacMini** [comment]
Result of [Integration 2](https://stlt.herokuapp.com/v1/xcs_deeplink/BranchMacMini.local/1d6f071064e67f7d4dee3ef2e1546cbd/1d6f071064e67f7d4dee3ef2e1677e26)
---
*Duration*: 2 minutes and 44 seconds
*Result*: All 165 tests passed, but please **fix 1 analyzer warning**.
*Test Coverage*: 64%

**Comment by BranchMacMini** [comment]
Result of [Integration 3](https://stlt.herokuapp.com/v1/xcs_deeplink/BranchMacMini.local/1d6f071064e67f7d4dee3ef2e1546cbd/1d6f071064e67f7d4dee3ef2e17ad9ba)
---
*Duration*: 2 minutes and 20 seconds
*Result*: **Build failed 1 test** out of 165

**Comment by BranchMacMini** [comment]
Result of [Integration 4](https://stlt.herokuapp.com/v1/xcs_deeplink/BranchMacMini.local/1d6f071064e67f7d4dee3ef2e1546cbd/1d6f071064e67f7d4dee3ef2e18d4c43)
---
*Duration*: 2 minutes and 38 seconds
*Result*: **Perfect build!** All 165 tests passed. :+1:
*Test Coverage*: 64%

**Comment by zeeshabnc** [comment]
@E-B-Smith Please provide more context either in the JIRA or this PR on what this is for and what we are doing. Light weight logging is not enough.

**Comment by E-B-Smith** [comment]
The bigger picture is that these lower level logging functions will be used as part of the planned crash detection and reporting.

I want to introduce usable parts to the crash detection in smaller PRs when practical rather than have one gigantic PR.

Right now, logging is handled through the BNCPreferenceHelper.  This PR separates logging from preferences so each part functionally does one thing.

This PR is based on logging code I've used for years, so it has some provenance.

**Comment by BranchMacMini** [comment]
Result of [Integration 5](https://stlt.herokuapp.com/v1/xcs_deeplink/BranchMacMini.local/1d6f071064e67f7d4dee3ef2e1546cbd/8584c1925d0f30c3bae2e4b6ba0af601)
---
*Duration*: 2 minutes and 55 seconds
*Result*: **Perfect build!** All 165 tests passed. :+1:
*Test Coverage*: 64%

**Comment by E-B-Smith** [comment]
@jdee We can add functionality as needed.  I want to keep it simple for now.

**Pull request merged**
