### PR TITLE
Limit app tracking (AIS-417)

### PR DESCRIPTION
**Pull request by E-B-Smith**

### CODE REVIEW

**Comment by BranchMacMini** [comment]
Result of [Integration 1](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/cf6883a0f9e873dc2469e7db0a866fe1/cf6883a0f9e873dc2469e7db0a8670ce)
---
*Duration*: 11 minutes and 49 seconds
*Result*: **2 errors, failing state: build-errors**

**Comment by BranchMacMini** [comment]
Result of [Integration 2](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/cf6883a0f9e873dc2469e7db0a866fe1/cf6883a0f9e873dc2469e7db0aa15f1f)
---
*Duration*: 10 minutes and 38 seconds
*Result*: **1 error, failing state: build-errors**

**Comment by BranchMacMini** [comment]
Result of [Integration 3](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/cf6883a0f9e873dc2469e7db0a866fe1/22338d2b4844ebc5791d27cef177246d)
---
*Duration*: 10 minutes and 52 seconds
*Result*: All 223 tests passed, but please **fix 1 warning**.
*Test Coverage*: 62%

**Comment by E-B-Smith** [comment]
The Android PR is https://github.com/BranchMetrics/android-branch-deep-linking/pull/506

**Comment by dmitrig01** [comment]
please update name per discussion in slack

**Comment by E-B-Smith** [comment]
@dmitrig01 Updated.

**Comment by BranchMacMini** [comment]
Result of [Integration 4](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/cf6883a0f9e873dc2469e7db0a866fe1/ee046aaccbd3e77c86e6d649584cf0f7)
---
*Duration*: 13 minutes and 48 seconds
*Result*: **Build failed 1 test** out of 223

**Comment by BranchMacMini** [comment]
Result of [Integration 5](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/cf6883a0f9e873dc2469e7db0a866fe1/ee046aaccbd3e77c86e6d64958762b05)
---
*Duration*: 11 minutes and 0 second
*Result*: All 223 tests passed, but please **fix 1 warning**.
*Test Coverage*: 62%

**Comment by dmitrig01** [comment]
i'm not really qualified to review iOS PRs but it looks good enough to me

**Comment by BranchMacMini** [comment]
Result of [Integration 6](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/cf6883a0f9e873dc2469e7db0a866fe1/ee046aaccbd3e77c86e6d64958b090eb)
---
*Duration*: 12 minutes and 38 seconds
*Result*: **1 error, failing state: build-errors**

**Comment by BranchMacMini** [comment]
Result of [Integration 6](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/cf6883a0f9e873dc2469e7db0a866fe1/ee046aaccbd3e77c86e6d64958b090eb)
---
*Duration*: 12 minutes and 38 seconds
*Result*: **1 error, failing state: build-errors**

**Comment by BranchMacMini** [comment]
Result of [Integration 8](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/cf6883a0f9e873dc2469e7db0a866fe1/273277f670f08a8d30e2233b02285ad5)
---
*Duration*: 12 minutes and 34 seconds
*Result*: All 223 tests passed, but please **fix 1 warning**.
*Test Coverage*: 63%

**Comment by BranchMacMini** [comment]
Result of [Integration 9](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/cf6883a0f9e873dc2469e7db0a866fe1/4fa2f9e5cd8a338771d6b82947d7fe51)
---
*Duration*: 10 minutes and 49 seconds
*Result*: All 223 tests passed, but please **fix 1 warning**.
*Test Coverage*: 63%

**Comment by BranchMacMini** [comment]
Result of [Integration 11](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/cf6883a0f9e873dc2469e7db0a866fe1/661e471225b72f6e73799a71f09cd9f3)
---
*Duration*: 11 minutes and 49 seconds
*Result*: All 223 tests passed, but please **fix 1 warning**.
*Test Coverage*: 63%

**Comment by mparul** [comment]
👍

**Pull request merged**
