### PR TITLE
INTENG-3579 Default dynamic links fix

### PR DESCRIPTION
**Pull request by agrimn**
By default, Dynamic links are created every time internet connectivity is down.
- Set forceLinkCreation to YES by default.
- Fixed indentation.

### CODE REVIEW

**Comment by BranchMacMini** [comment]
Result of [Integration 1](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/0bf1fc775fcb4dc220f39b63f14f253b/0bf1fc775fcb4dc220f39b63f14f300c)
---
*Duration*: 6 minutes and 56 seconds
*Result*: **Perfect build!** All 184 tests passed. :+1:
*Test Coverage*: 60%

**Comment by ahmednawar** [comment]
I am still confused. Why does forcing link creation generate a dynamic link by default? Don't we already generate dynamic (long) links in the case of network failures?

**Comment by E-B-Smith** [comment]
@ahmednawar @agrimn Agrim looked into this:  Apparently Android generated long links when there was a network failure, but iOS didn't.  Agrim made this change so that both SDKs worked the same.

**Comment by ahmednawar** [comment]
iOS does the same right now as well. If you enable Airplane mode, then try to generate a link on the testbed, you will get a long link.

**Pull request merged**
