### PR TITLE
Updated testbed-swift to swift 4 string handling.

### PR DESCRIPTION
**Pull request by E-B-Smith**

### CODE REVIEW

**Comment by BranchMacMini** [comment]
Result of [Integration 1](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/ccee3a03a506642ef5411203d5678419/ccee3a03a506642ef5411203d567933f)
---
*Duration*: 13 minutes and 27 seconds
*Result*: **Build failed 1 test** out of 223

**Comment by BranchMacMini** [comment]
Result of [Integration 1](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/ccee3a03a506642ef5411203d5678419/ccee3a03a506642ef5411203d567933f)
---
*Duration*: 13 minutes and 27 seconds
*Result*: **Build failed 1 test** out of 223

**Comment by BranchMacMini** [comment]
Result of [Integration 3](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/ccee3a03a506642ef5411203d5678419/ccee3a03a506642ef5411203d591f7d7)
---
*Duration*: 9 minutes and 30 seconds
*Result*: **Build failed 1 test** out of 223

**Comment by BranchMacMini** [comment]
Result of [Integration 4](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/ccee3a03a506642ef5411203d5678419/ccee3a03a506642ef5411203d5badabc)
---
*Duration*: 10 minutes and 27 seconds
*Result*: All 223 tests passed, but please **fix 1 warning**.
*Test Coverage*: 63%

**Comment by dwestgate** [comment]
👍

**Pull request merged**
