### PR TITLE
Add the ability to disable user tracking.

### PR DESCRIPTION
**Pull request by E-B-Smith**
* Added `setTrackingDisabled` and `trackingDisabled` methods to the Branch class to set and query the tracking state.
* Added the `BNCTrackingDisabledError` error code that's returned to callbacks when tracking is disabled.
* Added a `clearTrackingInformation` method to the preference helper class that clears user identifiable information from preferences.
* Changed some NSDictionaries to NSMutableDictionaries for crash safety: Storing nil to a mutable dictionary is not a crash.
* Added a 'Do not track' option to UITestBed.

### CODE REVIEW

**Comment by BranchMacMini** [comment]
Result of [Integration 1](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/43ad31181db5e867a69620364fce3cc2/43ad31181db5e867a69620364fce45d9)
---
*Duration*: 15 minutes and 36 seconds
*Result*: All 227 tests passed, but please **fix 2 warnings** and **1 analyzer warning**.
*Test Coverage*: 62%

**Comment by BranchMacMini** [comment]
Result of [Integration 2](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/43ad31181db5e867a69620364fce3cc2/43ad31181db5e867a69620364ff729c1)
---
*Duration*: 13 minutes and 28 seconds
*Result*: **2 errors, failing state: build-errors**

**Comment by BranchMacMini** [comment]
Result of [Integration 3](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/43ad31181db5e867a69620364fce3cc2/8f3e18ed1506d72c8b2f5a6eda4a2c2a)
---
*Duration*: 15 minutes and 51 seconds
*Result*: **Build failed 1 test** out of 227

**Comment by BranchMacMini** [comment]
Result of [Integration 4](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/43ad31181db5e867a69620364fce3cc2/8f3e18ed1506d72c8b2f5a6eda741d33)
---
*Duration*: 13 minutes and 9 seconds
*Result*: **Build failed 1 test** out of 227

**Comment by BranchMacMini** [comment]
Result of [Integration 5](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/43ad31181db5e867a69620364fce3cc2/8f3e18ed1506d72c8b2f5a6eda9e0fa8)
---
*Duration*: 11 minutes and 36 seconds
*Result*: All 227 tests passed, but please **fix 2 warnings**.
*Test Coverage*: 62%

**Comment by BranchMacMini** [comment]
Result of [Integration 6](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/43ad31181db5e867a69620364fce3cc2/1b77343b32a1796bc2c189cc4ba873a4)
---
*Duration*: 12 minutes and 43 seconds
*Result*: **Build failed 1 test** out of 227

**Comment by BranchMacMini** [comment]
Result of [Integration 6](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/43ad31181db5e867a69620364fce3cc2/1b77343b32a1796bc2c189cc4ba873a4)
---
*Duration*: 12 minutes and 43 seconds
*Result*: **Build failed 1 test** out of 227

**Comment by BranchMacMini** [comment]
Result of [Integration 8](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/43ad31181db5e867a69620364fce3cc2/8f577ec4510638554a564701b50e377c)
---
*Duration*: 15 minutes and 15 seconds
*Result*: All 227 tests passed, but please **fix 2 warnings**.
*Test Coverage*: 62%

**Comment by BranchMacMini** [comment]
Result of [Integration 9](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/43ad31181db5e867a69620364fce3cc2/c4a08d815bcaafc35de319aa0e22d970)
---
*Duration*: 14 minutes and 31 seconds
*Result*: **1 error, failing state: build-errors**

**Comment by BranchMacMini** [comment]
Result of [Integration 10](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/43ad31181db5e867a69620364fce3cc2/b1af2ffc6976b5fc3fb4acb32503ccef)
---
*Duration*: 15 minutes and 7 seconds
*Result*: **Build failed 1 test** out of 227

**Comment by BranchMacMini** [comment]
Result of [Integration 11](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/43ad31181db5e867a69620364fce3cc2/b1af2ffc6976b5fc3fb4acb32537f79f)
---
*Duration*: 13 minutes and 8 seconds
*Result*: All 227 tests passed, but please **fix 2 warnings**.
*Test Coverage*: 62%

**Comment by BranchMacMini** [comment]
Result of [Integration 12](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/43ad31181db5e867a69620364fce3cc2/b1af2ffc6976b5fc3fb4acb3256e8532)
---
*Duration*: 15 minutes and 7 seconds
*Result*: All 227 tests passed, but please **fix 3 warnings**.
*Test Coverage*: 62%

**Comment by BranchMacMini** [comment]
Result of [Integration 13](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/43ad31181db5e867a69620364fce3cc2/0055f016474377146e7896ea5cc50a4f)
---
*Duration*: 43 minutes and 54 seconds
*Result*: **2 errors, failing state: internal-processing-error**

**Comment by BranchMacMini** [comment]
Result of [Integration 14](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/43ad31181db5e867a69620364fce3cc2/0055f016474377146e7896ea5cc5b5a0)
---
*Duration*: 13 minutes and 13 seconds
*Result*: All 227 tests passed, but please **fix 2 warnings**.
*Test Coverage*: 62%

**Comment by BranchMacMini** [comment]
Result of [Integration 15](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/43ad31181db5e867a69620364fce3cc2/feafba8a0f345a08a7205e2a63173e96)
---
*Duration*: 32 minutes and 57 seconds
*Result*: All 227 tests passed, but please **fix 2 warnings**.
*Test Coverage*: 62%

**Comment by BranchMacMini** [comment]
Result of [Integration 16](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/43ad31181db5e867a69620364fce3cc2/feafba8a0f345a08a7205e2a6341b038)
---
*Duration*: 18 minutes and 23 seconds
*Result*: **Build failed 1 test** out of 227

**Comment by BranchMacMini** [comment]
Result of [Integration 17](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/43ad31181db5e867a69620364fce3cc2/feafba8a0f345a08a7205e2a63714b94)
---
*Duration*: 13 minutes and 3 seconds
*Result*: All 227 tests passed, but please **fix 2 warnings**.
*Test Coverage*: 62%

**Comment by BranchMacMini** [comment]
Result of [Integration 18](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/43ad31181db5e867a69620364fce3cc2/feafba8a0f345a08a7205e2a639bf8a9)
---
*Duration*: 13 minutes and 33 seconds
*Result*: All 227 tests passed, but please **fix 3 warnings**.
*Test Coverage*: 62%

**Comment by BranchMacMini** [comment]
Result of [Integration 19](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/43ad31181db5e867a69620364fce3cc2/feafba8a0f345a08a7205e2a63c6e05d)
---
*Duration*: 18 minutes and 38 seconds
*Result*: **Build failed 1 test** out of 227

**Comment by BranchMacMini** [comment]
Result of [Integration 20](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/43ad31181db5e867a69620364fce3cc2/feafba8a0f345a08a7205e2a63f69646)
---
*Duration*: 18 minutes and 25 seconds
*Result*: **Build failed 2 tests** out of 227

**Comment by sojanpr** [comment]
LGTM 👍

**Comment by BranchMacMini** [comment]
Result of [Integration 21](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/43ad31181db5e867a69620364fce3cc2/d3366f49994d670043bc59df3c2113a5)
---
*Duration*: 11 minutes and 52 seconds
*Result*: **Build failed 2 tests** out of 227

**Comment by BranchMacMini** [comment]
Result of [Integration 23](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/43ad31181db5e867a69620364fce3cc2/d3366f49994d670043bc59df3c765382)
---
*Duration*: 32 minutes and 25 seconds
*Result*: **Build failed 2 tests** out of 227

**Pull request merged**
