### PR TITLE
Adds Email HTML support to BranchActivityItemProvider

### PR DESCRIPTION
**Pull request by timbroder**
There are cases where you'd want to add text both before and after the link in an Email share; styling, intro, outro, or wrap the link in an <a> tag.

Given as there was already a special case for email with ```BRANCH_LINK_DATA_KEY_EMAIL_SUBJECT```, I've added a for more to customize the email further

### CODE REVIEW

**Comment by BranchMacMini** [comment]
Result of [Integration 1](https://stlt.herokuapp.com/v1/xcs_deeplink/BranchMacMini.local/31a324e1499ee1606146aafe8f3aceab/31a324e1499ee1606146aafe8f3ad6cc)
---
*Duration*: 3 minutes and 8 seconds
*Result*: **1 error, failing state: build-errors**

**Comment by timbroder** [comment]
I can't see what the build error is to try to fix:

image

**Comment by E-B-Smith** [comment]
Nice. Thanks for the PR @timbroder.  Don't worry about the Buildasaur error.  It's been flaky since the Xcode 8.3.1 upgrade.

**Comment by timbroder** [comment]
👍

**Comment by BranchMacMini** [comment]
Result of [Integration 5](https://stlt.herokuapp.com/v1/xcs_deeplink/BranchMacMini.local/31a324e1499ee1606146aafe8f3aceab/30100875d20faf229b7e6adcc80028ab)
---
*Duration*: 16 minutes and 50 seconds
*Result*: **1 error, failing state: build-errors**

**Comment by BranchMacMini** [comment]
Result of [Integration 1](https://stlt.herokuapp.com/v1/xcs_deeplink/BranchMacMini.local/9d628bd21bc7d253a85fa498263d4f44/9d628bd21bc7d253a85fa498263d5f55)
---
*Duration*: 1 minute and 3 seconds
*Result*: **-1 error, failing state: build-failed**

**Comment by BranchMacMini** [comment]
Result of [Integration 2](https://stlt.herokuapp.com/v1/xcs_deeplink/BranchMacMini.local/9d628bd21bc7d253a85fa498263d4f44/9d628bd21bc7d253a85fa498263f9057)
---
*Duration*: 19 seconds
*Result*: **-1 error, failing state: build-failed**

**Comment by BranchMacMini** [comment]
Result of [Integration 1](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/9d628bd21bc7d253a85fa49826879053/9d628bd21bc7d253a85fa49826879f21)
---
*Duration*: 5 minutes and 17 seconds
Build was **manually canceled**.

**Comment by BranchMacMini** [comment]
Result of [Integration 2](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/9d628bd21bc7d253a85fa49826879053/4671cb6175c07343ead50b38df005726)
---
*Duration*: 3 minutes and 28 seconds
*Result*: **1 error, failing state: build-errors**

**Comment by BranchMacMini** [comment]
Result of [Integration 3](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/9d628bd21bc7d253a85fa49826879053/4671cb6175c07343ead50b38df67742e)
---
*Duration*: 2 minutes and 55 seconds
*Result*: **Build failed 1 test** out of 169

**Comment by E-B-Smith** [comment]
@timbroder I moved this to #619 to merge against the staging branch.

**Pull request closed without merging**
