### PR TITLE
INTENG-3466 Fix for html tags in Dynamic links

### PR DESCRIPTION
**Pull request by agrimn**
URL encoded Base64 encoded link data that is generated when creating Dynamic links.

Exposed urlEncodedString from BNCEncodingUtils

### CODE REVIEW

**Comment by BranchMacMini** [comment]
Result of [Integration 1](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/3d8d9790a6195abf4b146dc4cc3df9d0/3d8d9790a6195abf4b146dc4cc3e07b3)
---
*Duration*: 7 minutes and 20 seconds
*Result*: **Build failed 1 test** out of 179

**Comment by BranchMacMini** [comment]
Result of [Integration 2](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/3d8d9790a6195abf4b146dc4cc3df9d0/3d8d9790a6195abf4b146dc4cc62e28b)
---
*Duration*: 6 minutes and 46 seconds
*Result*: **Build failed 1 test** out of 184

**Comment by ahmednawar** [comment]
looks good to me. Tests are failing though.

**Comment by agrimn** [comment]
@ahmednawar I just fixed the SDK tests. waiting for Buildasaur

**Comment by BranchMacMini** [comment]
Result of [Integration 3](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/3d8d9790a6195abf4b146dc4cc3df9d0/3d8d9790a6195abf4b146dc4cccaddb6)
---
*Duration*: 6 minutes and 42 seconds
*Result*: **Perfect build!** All 184 tests passed. :+1:
*Test Coverage*: 60%

**Pull request merged**
