### PR TITLE
Updated the BranchShareLink so the activity item children own the parent.

### PR DESCRIPTION
**Pull request by E-B-Smith**

### CODE REVIEW

**Comment by BranchMacMini** [comment]
Result of [Integration 1](https://stlt.herokuapp.com/v1/xcs_deeplink/BranchMacMini.local/a1c05e3baf6054119de6aca66ebf4e11/a1c05e3baf6054119de6aca66ebf54d5)
---
*Duration*: 1 minute and 10 seconds
*Result*: **-1 error, failing state: build-failed**

**Comment by E-B-Smith** [comment]
iOS 10.3 / Xcode 8.3 broke the QA bot so don’t worry if integrations fail (for now).

**Comment by BranchMacMini** [comment]
Result of [Integration 1](https://stlt.herokuapp.com/v1/xcs_deeplink/BranchMacMini.local/a1c05e3baf6054119de6aca66ec5905e/a1c05e3baf6054119de6aca66ec60752)
---
*Duration*: 4 minutes and 31 seconds
*Result*: **Build failed 2 tests** out of 169

**Comment by BranchMacMini** [comment]
Result of [Integration 2](https://stlt.herokuapp.com/v1/xcs_deeplink/BranchMacMini.local/a1c05e3baf6054119de6aca66ec5905e/c1bd197e0975b92c863c457f5f0a6346)
---
*Duration*: 2 minutes and 42 seconds
*Result*: **2 errors, failing state: build-errors**

**Pull request merged**
