### PR TITLE
Fixed reward and system observer unit tests.

### PR DESCRIPTION
**Pull request by E-B-Smith**

### CODE REVIEW

**Comment by BranchMacMini** [comment]
Result of [Integration 1](https://stlt.herokuapp.com/v1/xcs_deeplink/BranchMacMini.local/ea5ae53b09b7154843780a0f5b041785/ea5ae53b09b7154843780a0f5b043f03)
---
*Duration*: 9 minutes and 12 seconds
*Result*: **1 error, failing state: build-errors**

**Comment by BranchMacMini** [comment]
Result of [Integration 2](https://stlt.herokuapp.com/v1/xcs_deeplink/BranchMacMini.local/ea5ae53b09b7154843780a0f5b041785/ea5ae53b09b7154843780a0f5b582df0)
---
*Duration*: 8 minutes and 28 seconds
*Result*: **Build failed 6 tests** out of 143

**Comment by BranchMacMini** [comment]
Result of [Integration 3](https://stlt.herokuapp.com/v1/xcs_deeplink/BranchMacMini.local/ea5ae53b09b7154843780a0f5b041785/ea5ae53b09b7154843780a0f5b8e124a)
---
*Duration*: 8 minutes and 14 seconds
*Result*: **Build failed 2 tests** out of 143

**Comment by BranchMacMini** [comment]
Result of [Integration 4](https://stlt.herokuapp.com/v1/xcs_deeplink/BranchMacMini.local/ea5ae53b09b7154843780a0f5b041785/ea5ae53b09b7154843780a0f5ba34ef5)
---
*Duration*: 8 minutes and 2 seconds
*Result*: **Build failed 2 tests** out of 143

**Comment by BranchMacMini** [comment]
Result of [Integration 5](https://stlt.herokuapp.com/v1/xcs_deeplink/BranchMacMini.local/ea5ae53b09b7154843780a0f5b041785/ea5ae53b09b7154843780a0f5bb91ed8)
---
*Duration*: 6 minutes and 20 seconds
*Result*: **1 error, failing state: build-errors**

**Comment by BranchMacMini** [comment]
Result of [Integration 5](https://stlt.herokuapp.com/v1/xcs_deeplink/BranchMacMini.local/ea5ae53b09b7154843780a0f5b041785/ea5ae53b09b7154843780a0f5bb91ed8)
---
*Duration*: 6 minutes and 20 seconds
*Result*: **1 error, failing state: build-errors**

**Comment by BranchMacMini** [comment]
Result of [Integration 7](https://stlt.herokuapp.com/v1/xcs_deeplink/BranchMacMini.local/ea5ae53b09b7154843780a0f5b041785/ea5ae53b09b7154843780a0f5bce10ea)
---
*Duration*: 6 minutes and 27 seconds
*Result*: **1 error, failing state: build-errors**

**Comment by BranchMacMini** [comment]
Result of [Integration 8](https://stlt.herokuapp.com/v1/xcs_deeplink/BranchMacMini.local/ea5ae53b09b7154843780a0f5b041785/d9eb4bbc2e9d2ba50a7dd6998a004960)
---
*Duration*: 8 minutes and 40 seconds
*Result*: **Build failed 2 tests** out of 143

**Comment by BranchMacMini** [comment]
Result of [Integration 9](https://stlt.herokuapp.com/v1/xcs_deeplink/BranchMacMini.local/ea5ae53b09b7154843780a0f5b041785/d9eb4bbc2e9d2ba50a7dd6998a16a3aa)
---
*Duration*: 8 minutes and 54 seconds
*Result*: **Build failed 3 tests** out of 143

**Comment by BranchMacMini** [comment]
Result of [Integration 9](https://stlt.herokuapp.com/v1/xcs_deeplink/BranchMacMini.local/ea5ae53b09b7154843780a0f5b041785/d9eb4bbc2e9d2ba50a7dd6998a16a3aa)
---
*Duration*: 8 minutes and 54 seconds
*Result*: **Build failed 3 tests** out of 143

**Comment by BranchMacMini** [comment]
Result of [Integration 11](https://stlt.herokuapp.com/v1/xcs_deeplink/BranchMacMini.local/ea5ae53b09b7154843780a0f5b041785/d9eb4bbc2e9d2ba50a7dd6998a89ef27)
---
*Duration*: 12 minutes and 17 seconds
*Result*: **Build failed 6 tests** out of 143

**Comment by BranchMacMini** [comment]
Result of [Integration 11](https://stlt.herokuapp.com/v1/xcs_deeplink/BranchMacMini.local/ea5ae53b09b7154843780a0f5b041785/d9eb4bbc2e9d2ba50a7dd6998a89ef27)
---
*Duration*: 12 minutes and 17 seconds
*Result*: **Build failed 6 tests** out of 143

**Comment by BranchMacMini** [comment]
Result of [Integration 11](https://stlt.herokuapp.com/v1/xcs_deeplink/BranchMacMini.local/ea5ae53b09b7154843780a0f5b041785/d9eb4bbc2e9d2ba50a7dd6998a89ef27)
---
*Duration*: 12 minutes and 17 seconds
*Result*: **Build failed 6 tests** out of 143

**Comment by BranchMacMini** [comment]
Result of [Integration 15](https://stlt.herokuapp.com/v1/xcs_deeplink/BranchMacMini.local/ea5ae53b09b7154843780a0f5b041785/1d6f071064e67f7d4dee3ef2e11cf08b)
---
*Duration*: 2 minutes and 53 seconds
*Result*: **Build failed 1 test** out of 143

**Comment by ahmednawar** [comment]
👍

**Comment by BranchMacMini** [comment]
Result of [Integration 1](https://stlt.herokuapp.com/v1/xcs_deeplink/BranchMacMini.local/1d6f071064e67f7d4dee3ef2e131c2ff/1d6f071064e67f7d4dee3ef2e131d13f)
---
*Duration*: 4 minutes and 15 seconds
*Result*: **Perfect build!** All 143 tests passed. :+1:
*Test Coverage*: 60%

**Pull request merged**
