### PR TITLE
Use modules instead of module map for better Swift integration.

### PR DESCRIPTION
**Pull request by E-B-Smith**
* This change should be benign but may impact integration with React or Cordova.  Comments?

### CODE REVIEW

**Comment by E-B-Smith** [comment]
This PR replaces the old PR #590 , since that PR is so old.

**Comment by BranchMacMini** [comment]
Result of [Integration 2](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/9e9b48fe243d3106a47e54ecc500b858/9e9b48fe243d3106a47e54ecc500e055)
---
*Duration*: 8 minutes and 4 seconds
*Result*: All 199 tests passed, but please **fix 1 warning**.
*Test Coverage*: 60%

**Comment by BranchMacMini** [comment]
Result of [Integration 3](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/9e9b48fe243d3106a47e54ecc500b858/9e9b48fe243d3106a47e54ecc526523e)
---
*Duration*: 7 minutes and 49 seconds
*Result*: **Perfect build!** All 199 tests passed. :+1:
*Test Coverage*: 60%

**Comment by jdee** [comment]
I checked the most likely problem case with React Native, and it builds fine. I want to take a little time to review, but it looks good at the moment.

**Comment by BranchMacMini** [comment]
Result of [Integration 4](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/9e9b48fe243d3106a47e54ecc500b858/9e9b48fe243d3106a47e54ecc5dfcf46)
---
*Duration*: 7 minutes and 58 seconds
*Result*: **Perfect build!** All 199 tests passed. :+1:
*Test Coverage*: 61%

**Comment by BranchMacMini** [comment]
Result of [Integration 5](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/9e9b48fe243d3106a47e54ecc500b858/da3dd52f59d965e4aeb7a76e1f0019ae)
---
*Duration*: 8 minutes and 40 seconds
*Result*: **Build failed 3 tests** out of 202

**Comment by BranchMacMini** [comment]
Result of [Integration 6](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/9e9b48fe243d3106a47e54ecc500b858/da3dd52f59d965e4aeb7a76e1f722184)
---
*Duration*: 8 minutes and 26 seconds
*Result*: **Perfect build!** All 202 tests passed. :+1:
*Test Coverage*: 61%

**Pull request merged**
