### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by RunesReader**
Corrects pod file record.

Please submit your PR against the `staging` branch.

### CODE REVIEW

**Comment by BranchMacMini** [comment]
Result of [Integration 1](https://stlt.herokuapp.com/v1/xcs_deeplink/BranchMacMini.local/ea5ae53b09b7154843780a0f5b70c519/ea5ae53b09b7154843780a0f5b70c65c)
---
*Duration*: 8 minutes and 41 seconds
*Result*: **1 error, failing state: build-errors**

**Comment by RunesReader** [comment]
It's all very strange. I corrected only README.md file! Why "Buildasaur — Build error!"?

**Comment by E-B-Smith** [comment]
Thank you for updating the README file.

I just brought Buildasaur online last night and there's still a config error.  Nothing for you to worry about.

**Comment by E-B-Smith** [comment]
👍

**Comment by E-B-Smith** [comment]
Added in a different PR.

**Pull request closed without merging**
