### PR TITLE
Fix update dates DEVEX-58

### PR DESCRIPTION
**Pull request by E-B-Smith**

### CODE REVIEW

**Comment by BranchMacMini** [comment]
Result of [Integration 1](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/97ff85cbd7416e2cada11e3b46c556dc/97ff85cbd7416e2cada11e3b46c5611c)
---
*Duration*: 5 minutes and 55 seconds
*Result*: **1 error, failing state: build-errors**

**Comment by BranchMacMini** [comment]
Result of [Integration 2](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/97ff85cbd7416e2cada11e3b46c556dc/97ff85cbd7416e2cada11e3b46c5f9a9)
---
*Duration*: 11 minutes and 50 seconds
*Result*: **Build failed 1 test** out of 220

**Comment by BranchMacMini** [comment]
Result of [Integration 3](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/97ff85cbd7416e2cada11e3b46c556dc/97ff85cbd7416e2cada11e3b46ee27c3)
---
*Duration*: 11 minutes and 41 seconds
*Result*: All 220 tests passed, but please **fix 2 warnings**.
*Test Coverage*: 63%

**Comment by BranchMacMini** [comment]
Result of [Integration 4](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/97ff85cbd7416e2cada11e3b46c556dc/6123e4f7b956aedeaf63112c4e3584f2)
---
*Duration*: 11 minutes and 46 seconds
*Result*: All 220 tests passed, but please **fix 2 warnings**.
*Test Coverage*: 63%

**Comment by BranchMacMini** [comment]
Result of [Integration 5](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/97ff85cbd7416e2cada11e3b46c556dc/6123e4f7b956aedeaf63112c4e61ee26)
---
*Duration*: 10 minutes and 40 seconds
*Result*: All 220 tests passed, but please **fix 2 warnings**.
*Test Coverage*: 63%

**Comment by BranchMacMini** [comment]
Result of [Integration 6](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/97ff85cbd7416e2cada11e3b46c556dc/6123e4f7b956aedeaf63112c4e8bcfcb)
---
*Duration*: 12 minutes and 25 seconds
*Result*: **Build failed 1 test** out of 220

**Comment by BranchMacMini** [comment]
Result of [Integration 6](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/97ff85cbd7416e2cada11e3b46c556dc/6123e4f7b956aedeaf63112c4e8bcfcb)
---
*Duration*: 12 minutes and 25 seconds
*Result*: **Build failed 1 test** out of 220

**Comment by BranchMacMini** [comment]
Result of [Integration 9](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/97ff85cbd7416e2cada11e3b46c556dc/a1d6722c964fdc588004690b5a1ac2f5)
---
*Duration*: 14 minutes and 22 seconds
*Result*: **Build failed 3 tests** out of 220

**Comment by BranchMacMini** [comment]
Result of [Integration 10](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/97ff85cbd7416e2cada11e3b46c556dc/a1d6722c964fdc588004690b5a432820)
---
*Duration*: 12 minutes and 16 seconds
*Result*: **Build failed 1 test** out of 220

**Comment by sojanpr** [comment]
LGTM 👍

**Pull request merged**
