### PR TITLE
[DO NOT MERGE] WebViewExample with Crashlytics

### PR DESCRIPTION
**Pull request by jdee**
This is the test harness I've been using to test with Crashlytics.

Because of difficulties getting symbolicated crash reports with Debug builds, I've been archiving and distributing this through Crashlytics to my phone. I've modified it to use the Branch signing team. Archiving requires access to one of Branch's distro certs in the Apple portal, which I think requires admin access or something. At any rate, I don't have it. Anyone testing that way needs a distro cert or another way of testing.

There is a Crash button at the upper right of the landing screen that lets you generate a crash for testing. Just launch the app again after the crash to upload the report and see it in the Fabric portal.

I've been using Fastlane to set up the project. If you want to change the Branch params, you can just edit `Examples/WebViewExample/fastlane/Branchfile` and then in `Examples/WebViewExample` run

```bash
bundle install
bundle exec fastlane setup
```

There are also some reporting utilities in `BNCSystemObserver` that I've been using to count total and free memory. Crashlytics already includes free memory reporting, so I didn't bother to include this in recent PRs, but it could be included in the SDK if it's deemed sufficiently useful.

I'll add more notes in the Google doc.

### CODE REVIEW

**Comment by BranchMacMini** [comment]
Result of [Integration 2](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/850e42354b605420e32acc68843bd25a/850e42354b605420e32acc68843be1e2)
---
*Duration*: 10 minutes and 16 seconds
*Result*: **1 error, failing state: build-errors**

**Comment by BranchMacMini** [comment]
Result of [Integration 3](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/850e42354b605420e32acc68843bd25a/850e42354b605420e32acc6884b64c90)
---
*Duration*: 7 minutes and 4 seconds
*Result*: **Perfect build!** All 181 tests passed. :+1:
*Test Coverage*: 58%

**Comment by BranchMacMini** [comment]
Result of [Integration 4](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/850e42354b605420e32acc68843bd25a/850e42354b605420e32acc6884fb4694)
---
*Duration*: 7 minutes and 44 seconds
*Result*: **1 error, failing state: build-errors**

**Comment by E-B-Smith** [comment]
Thanks for the example.

**Pull request closed without merging**
