### PR TITLE
Deeplink validator

### PR DESCRIPTION
**Pull request by ruthmpardee**
@E-B-Smith This definitely needs revision, thanks for looking at it!

### CODE REVIEW

**Comment by BranchMacMini** [comment]
Result of [Integration 1](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/027c3b7dd5007b8a0e33f24237e1e975/027c3b7dd5007b8a0e33f24237e1f4f9)
---
*Duration*: 2 minutes and 7 seconds
*Result*: **1 error, failing state: build-errors**

**Comment by BranchMacMini** [comment]
Result of [Integration 2](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/027c3b7dd5007b8a0e33f24237e1e975/1a5bd5297075d43f0a9f1b1272e18390)
---
*Duration*: 1 minute and 19 seconds
*Result*: **1 error, failing state: build-errors**

**Comment by rmpardee** [comment]
@derrickstaten we should work on this at some point?

**Comment by E-B-Smith** [comment]
I'd love to get this going too.  Let me know what you need.  Does this need a new end point? Also, it doesn't compile right now.  What's it missing?

**Comment by BranchMacMini** [comment]
Result of [Integration 3](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/027c3b7dd5007b8a0e33f24237e1e975/4a950b5436627d63296817d0a0952e9c)
---
*Duration*: 2 minutes and 30 seconds
*Result*: **1 error, failing state: build-errors**

**Comment by E-B-Smith** [comment]
It looks like this needs some backend support too?

**Comment by BranchMacMini** [comment]
Result of [Integration 4](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/027c3b7dd5007b8a0e33f24237e1e975/94f4d79e542abd2c36db14000475b36b)
---
*Duration*: 2 minutes and 48 seconds
*Result*: **2 errors, failing state: build-errors**

**Comment by BranchMacMini** [comment]
Result of [Integration 5](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/027c3b7dd5007b8a0e33f24237e1e975/94f4d79e542abd2c36db140004768326)
---
*Duration*: 2 minutes and 48 seconds
*Result*: **2 errors, failing state: build-errors**

**Comment by BranchMacMini** [comment]
Result of [Integration 6](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/027c3b7dd5007b8a0e33f24237e1e975/df7c12f52d62f413aba10c381146a94f)
---
*Duration*: 12 minutes and 5 seconds
*Result*: All 223 tests passed, but please **fix 2 warnings**.
*Test Coverage*: 62%

**Comment by agrimn** [comment]
Hey, @E-B-Smith this is ready for review. Let me know if this is missing something.

**Comment by BranchMacMini** [comment]
Result of [Integration 7](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/027c3b7dd5007b8a0e33f24237e1e975/97ff85cbd7416e2cada11e3b463dba49)
---
*Duration*: 12 minutes and 15 seconds
*Result*: All 223 tests passed, but please **fix 2 warnings**.
*Test Coverage*: 62%

**Comment by agrimn** [comment]
@E-B-Smith updated this PR according to our discussion today.

**Comment by BranchMacMini** [comment]
Result of [Integration 8](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/027c3b7dd5007b8a0e33f24237e1e975/97ff85cbd7416e2cada11e3b46717a03)
---
*Duration*: 12 minutes and 1 second
*Result*: All 223 tests passed, but please **fix 2 warnings**.
*Test Coverage*: 63%

**Comment by davisjackie321** [comment]
Fix

**Comment by BranchMacMini** [comment]
Result of [Integration 9](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/027c3b7dd5007b8a0e33f24237e1e975/a1d6722c964fdc588004690b5a6d8f11)
---
*Duration*: 12 minutes and 13 seconds
*Result*: All 224 tests passed, but please **fix 2 warnings**.
*Test Coverage*: 62%

**Comment by E-B-Smith** [comment]
@agrimn Can you fix the '&validate=true' browser/app loop that happens?

**Comment by agrimn** [comment]
Hey @E-B-Smith I just pushed an update that should prevent the popup from appearing.

**Comment by BranchMacMini** [comment]
Result of [Integration 10](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/027c3b7dd5007b8a0e33f24237e1e975/d636e119dee43da9335f6269e0155bc2)
---
*Duration*: 11 minutes and 1 second
*Result*: **Build failed 2 tests** out of 224

**Comment by agrimn** [comment]
Seems like the tests failed because of a timeout.

**Comment by E-B-Smith** [comment]
Yep -- The Mac Mini CI times out a lot now.  It needs to be upgraded to the latest Xcode but I haven't had time to mess with it.

**Comment by BranchMacMini** [comment]
Result of [Integration 11](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/027c3b7dd5007b8a0e33f24237e1e975/d636e119dee43da9335f6269e04379e1)
---
*Duration*: 11 minutes and 57 seconds
*Result*: **1 error, failing state: build-errors**

**Comment by BranchMacMini** [comment]
Result of [Integration 12](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/027c3b7dd5007b8a0e33f24237e1e975/d636e119dee43da9335f6269e065d635)
---
*Duration*: 11 minutes and 17 seconds
*Result*: **Build failed 1 test** out of 224

**Comment by BranchMacMini** [comment]
Result of [Integration 14](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/027c3b7dd5007b8a0e33f24237e1e975/fe902cbba44b59ff95b81a6401aebfad)
---
*Duration*: 12 minutes and 3 seconds
*Result*: **Build failed 1 test** out of 220

**Comment by BranchMacMini** [comment]
Result of [Integration 15](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/027c3b7dd5007b8a0e33f24237e1e975/fe902cbba44b59ff95b81a6401d6f71a)
---
*Duration*: 11 minutes and 22 seconds
*Result*: All 220 tests passed, but please **fix 2 warnings**.
*Test Coverage*: 62%

**Pull request merged**
