### PR TITLE
Don't print HTTP status 404 error pages because it looks like an error.

### PR DESCRIPTION
**Pull request by E-B-Smith**

### CODE REVIEW

**Comment by E-B-Smith** [comment]
@sojanpr

**Comment by BranchMacMini** [comment]
Result of [Integration 1](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/8f577ec4510638554a564701b5cec28d/8f577ec4510638554a564701b5cec2fe)
---
*Duration*: 18 minutes and 33 seconds
*Result*: **Build failed 1 test** out of 227

**Comment by BranchMacMini** [comment]
Result of [Integration 2](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/8f577ec4510638554a564701b5cec28d/8f577ec4510638554a564701b5f82d17)
---
*Duration*: 14 minutes and 19 seconds
*Result*: **Build failed 3 tests** out of 227

**Comment by sojanpr** [comment]
LGTM 👍

**Pull request merged**
