### PR TITLE
[AIS-306] Localizable strings for the SDK

### PR DESCRIPTION
**Pull request by parthkalavadia**
String Localization module created, supporting the static SDK.
Though the string literals to support different languages needs to be added and the localization function(BNCLocalizedString("string")) needs to be called everywhere in the SDK.

### CODE REVIEW

**Comment by BranchMacMini** [comment]
Result of [Integration 1](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/dedc21f4546ce2a7c67b4b45262b8475/dedc21f4546ce2a7c67b4b45262b8cd4)
---
*Duration*: 5 minutes and 50 seconds
*Result*: **Perfect build!** All 179 tests passed. :+1:
*Test Coverage*: 57%

**Comment by E-B-Smith** [comment]
Can you write some unit tests for this?

**Comment by BranchMacMini** [comment]
Result of [Integration 2](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/dedc21f4546ce2a7c67b4b45262b8475/40294f4db6a6c8ac6f2d52fa563aa00c)
---
*Duration*: 7 minutes and 9 seconds
*Result*: **Build failed 2 tests** out of 185

**Comment by BranchMacMini** [comment]
Result of [Integration 3](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/dedc21f4546ce2a7c67b4b45262b8475/40294f4db6a6c8ac6f2d52fa565c9f65)
---
*Duration*: 6 minutes and 14 seconds
*Result*: **Build failed 2 tests** out of 185

**Comment by BranchMacMini** [comment]
Result of [Integration 4](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/dedc21f4546ce2a7c67b4b45262b8475/40294f4db6a6c8ac6f2d52fa5683c301)
---
*Duration*: 6 minutes and 37 seconds
*Result*: **Perfect build!** All 185 tests passed. :+1:
*Test Coverage*: 58%

**Comment by BranchMacMini** [comment]
Result of [Integration 5](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/dedc21f4546ce2a7c67b4b45262b8475/43c18a317125f07963a26d4d2ade3b72)
---
*Duration*: 1 minute and 54 seconds
*Result*: **4 errors, failing state: build-errors**

**Comment by BranchMacMini** [comment]
Result of [Integration 6](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/dedc21f4546ce2a7c67b4b45262b8475/43c18a317125f07963a26d4d2adedc8f)
---
*Duration*: 1 minute and 46 seconds
*Result*: **4 errors, failing state: build-errors**

**Comment by BranchMacMini** [comment]
Result of [Integration 7](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/dedc21f4546ce2a7c67b4b45262b8475/c8e561f6311c1c559ca1339dc84ce848)
---
*Duration*: 6 minutes and 55 seconds
*Result*: **Perfect build!** All 184 tests passed. :+1:
*Test Coverage*: 60%

**Comment by BranchMacMini** [comment]
Result of [Integration 8](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/dedc21f4546ce2a7c67b4b45262b8475/c8e561f6311c1c559ca1339dc8920211)
---
*Duration*: 6 minutes and 19 seconds
*Result*: **Perfect build!** All 187 tests passed. :+1:
*Test Coverage*: 61%

**Comment by BranchMacMini** [comment]
Result of [Integration 9](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/dedc21f4546ce2a7c67b4b45262b8475/c8e561f6311c1c559ca1339dc8b824dc)
---
*Duration*: 7 minutes and 10 seconds
*Result*: **Perfect build!** All 187 tests passed. :+1:
*Test Coverage*: 60%

**Comment by BranchMacMini** [comment]
Result of [Integration 10](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/dedc21f4546ce2a7c67b4b45262b8475/3d8d9790a6195abf4b146dc4cca6ced7)
---
*Duration*: 6 minutes and 20 seconds
*Result*: **Perfect build!** All 189 tests passed. :+1:
*Test Coverage*: 61%

**Comment by BranchMacMini** [comment]
Result of [Integration 11](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/dedc21f4546ce2a7c67b4b45262b8475/77ca53d7b0df82cb52d0785ab198c6b6)
---
*Duration*: 6 minutes and 20 seconds
*Result*: **Perfect build!** All 189 tests passed. :+1:
*Test Coverage*: 61%

**Comment by BranchMacMini** [comment]
Result of [Integration 12](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/dedc21f4546ce2a7c67b4b45262b8475/0a5c72c332d8d1933d4f4965736ca270)
---
*Duration*: 6 minutes and 31 seconds
*Result*: **Build failed 1 test** out of 191

**Comment by E-B-Smith** [comment]
Let's go over this PR tomorrow, Thursday when you get time.

**Comment by BranchMacMini** [comment]
Result of [Integration 13](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/dedc21f4546ce2a7c67b4b45262b8475/b53de82f295e7dcac1c9985afe8120d8)
---
*Duration*: 6 minutes and 13 seconds
*Result*: **Perfect build!** All 191 tests passed. :+1:
*Test Coverage*: 61%

**Comment by BranchMacMini** [comment]
Result of [Integration 14](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/dedc21f4546ce2a7c67b4b45262b8475/b53de82f295e7dcac1c9985afec8ef3f)
---
*Duration*: 6 minutes and 18 seconds
*Result*: **Perfect build!** All 191 tests passed. :+1:
*Test Coverage*: 61%

**Comment by E-B-Smith** [comment]
Thanks for all the work that everyone did on this. @parthkalavadia @MiluchOK @Zhukn1 .

**Pull request merged**
