### PR TITLE
[Don't Merge] Condition removed to check title and canonicalId - INTENG-3409

### PR DESCRIPTION
**Pull request by parthkalavadia**
Condition removed to check title and canonicalId while creating shortUrl in Branch.

### CODE REVIEW

**Comment by BranchMacMini** [comment]
Result of [Integration 1](https://stlt.herokuapp.com/v1/xcs_deeplink/qabot.stage.branch.io/b388335146db7e936b7215574da4f84e/b388335146db7e936b7215574da503dd)
---
*Duration*: 4 minutes and 50 seconds
*Result*: **Perfect build!** All 179 tests passed. :+1:
*Test Coverage*: 57%

**Comment by aaustin** [comment]
Messaged you asking for a bit more explanation for this change.

**Comment by E-B-Smith** [comment]
So these fields are used to de-dup links -- Awesome.  Now we now.

Let's figure out the right we to do this and why Android isn't doing it.

**Comment by E-B-Smith** [comment]
This will break existing compiles.  Better to let it silently fail?

**Pull request closed without merging**
