### PR TITLE
Fix keyboard hiding

### PR DESCRIPTION
**Pull request by vdugnist**
We start our application with active keyboard. After request to branch, our keyboard hides on calling `[self.secondWindow makeKeyWindow]` inside.
You can add SFSafariController as child view controller to prevent this.

### CODE REVIEW

**Comment by vdugnist** [comment]
In attached videos I close tutorial, tap on camera request, accept it.
Before: https://youtu.be/wuOrgTx9Frs
After: https://youtu.be/jE10DbVHTlo

**Comment by E-B-Smith** [comment]
@vdugnist  Thank you for your patch!

We have a fix for this that is beta testing right now.
If you'd test our fix for this to make sure it fixes your problem it would be a huge help.

Here's the info for getting our beta code:
https://github.com/BranchMetrics/ios-branch-deep-linking/wiki/The-SDK-Beta-Project

**Comment by vdugnist** [comment]
@E-B-Smith beta works well. Can I use it in production right now or it's better to use current stable version with my fix?

**Comment by E-B-Smith** [comment]
This is the version that we will push to production provided no significant problems are found.

It's been tested on iOS 8/9/10.  I would love some feedback so I can release it soon!

**Comment by vdugnist** [comment]
Ok, thx!

**Comment by E-B-Smith** [comment]
Thanks : Please send me feedback either way!

**Comment by vdugnist** [comment]
@E-B-Smith I've tried to run tests before PR, but it looks like they call outdated methods.
We'll test current beta and I'll give feedback in a few days.

**Comment by E-B-Smith** [comment]
@vdugnist Great! Thanks.

**Pull request closed without merging**
